version: '2'
services:
  mosquitto:
    image: monstrenyatko/rpi-mosquitto-auth
    container_name: mosquitto
    volumes:
      - mosquitto-data:/mosquitto/data
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    restart: unless-stopped
volumes:
  mosquitto-data:
    external: true